package com.vibe.jobs.crawler.domain;

import java.time.Instant;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

public class CrawlerBlueprintDraft {

    private final String code;
    private final String name;
    private final String entryUrl;
    private final int concurrencyLimit;
    private final boolean enabled;
    private final String parserTemplateCode;
    private final String configJson;
    private final String draftConfigJson;
    private final String lastTestReportJson;
    private final CrawlerBlueprintStatus status;
    private final boolean autoGenerated;
    private final String generatedBy;
    private final Instant generatedAt;
    private final Instant createdAt;
    private final Instant updatedAt;

    public CrawlerBlueprintDraft(String code,
                                 String name,
                                 String entryUrl,
                                 int concurrencyLimit,
                                 boolean enabled,
                                 String parserTemplateCode,
                                 String configJson,
                                 String draftConfigJson,
                                 String lastTestReportJson,
                                 CrawlerBlueprintStatus status,
                                 boolean autoGenerated,
                                 String generatedBy,
                                 Instant generatedAt,
                                 Instant createdAt,
                                 Instant updatedAt) {
        this.code = normalize(code);
        this.name = normalize(name);
        this.entryUrl = normalize(entryUrl);
        this.concurrencyLimit = concurrencyLimit <= 0 ? 1 : concurrencyLimit;
        this.enabled = enabled;
        this.parserTemplateCode = normalize(parserTemplateCode);
        this.configJson = configJson == null ? "" : configJson;
        this.draftConfigJson = draftConfigJson == null ? "" : draftConfigJson;
        this.lastTestReportJson = lastTestReportJson == null ? "" : lastTestReportJson;
        this.status = status == null ? CrawlerBlueprintStatus.ACTIVE : status;
        this.autoGenerated = autoGenerated;
        this.generatedBy = normalize(generatedBy);
        this.generatedAt = generatedAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    private String normalize(String value) {
        return value == null ? "" : value.trim();
    }

    public String code() {
        return code;
    }

    public String name() {
        return name;
    }

    public String entryUrl() {
        return entryUrl;
    }

    public int concurrencyLimit() {
        return concurrencyLimit;
    }

    public boolean enabled() {
        return enabled;
    }

    public String parserTemplateCode() {
        return parserTemplateCode;
    }

    public String configJson() {
        return configJson;
    }

    public String draftConfigJson() {
        return draftConfigJson;
    }

    public String lastTestReportJson() {
        return lastTestReportJson;
    }

    public CrawlerBlueprintStatus status() {
        return status;
    }

    public boolean autoGenerated() {
        return autoGenerated;
    }

    public String generatedBy() {
        return generatedBy;
    }

    public Optional<Instant> generatedAt() {
        return Optional.ofNullable(generatedAt);
    }

    public Optional<Instant> createdAt() {
        return Optional.ofNullable(createdAt);
    }

    public Optional<Instant> updatedAt() {
        return Optional.ofNullable(updatedAt);
    }

    public CrawlerBlueprintDraft markGenerating(String operator) {
        return new CrawlerBlueprintDraft(
                code,
                name,
                entryUrl,
                concurrencyLimit,
                false,
                parserTemplateCode,
                configJson,
                draftConfigJson,
                lastTestReportJson,
                CrawlerBlueprintStatus.DRAFT,
                true,
                operator == null ? generatedBy : operator,
                generatedAt,
                createdAt,
                updatedAt
        );
    }

    public CrawlerBlueprintDraft refreshForGeneration(String newEntryUrl, String newName, String operator) {
        return new CrawlerBlueprintDraft(
                code,
                newName == null || newName.isBlank() ? name : newName.trim(),
                newEntryUrl == null || newEntryUrl.isBlank() ? entryUrl : newEntryUrl.trim(),
                concurrencyLimit,
                false,
                parserTemplateCode,
                configJson,
                draftConfigJson,
                lastTestReportJson,
                CrawlerBlueprintStatus.DRAFT,
                true,
                operator == null ? generatedBy : operator,
                generatedAt,
                createdAt,
                Instant.now()
        );
    }

    public CrawlerBlueprintDraft withDraftResult(String draftConfigJson,
                                                 String reportJson,
                                                 Instant completedAt,
                                                 String operator) {
        return new CrawlerBlueprintDraft(
                code,
                name,
                entryUrl,
                concurrencyLimit,
                enabled,
                parserTemplateCode,
                configJson,
                draftConfigJson,
                reportJson,
                CrawlerBlueprintStatus.READY,
                true,
                operator == null ? generatedBy : operator,
                completedAt,
                createdAt,
                completedAt
        );
    }

    public CrawlerBlueprintDraft markFailed(String reportJson, String operator) {
        return new CrawlerBlueprintDraft(
                code,
                name,
                entryUrl,
                concurrencyLimit,
                enabled,
                parserTemplateCode,
                configJson,
                draftConfigJson,
                reportJson,
                CrawlerBlueprintStatus.FAILED,
                true,
                operator == null ? generatedBy : operator,
                generatedAt,
                createdAt,
                updatedAt
        );
    }

    public CrawlerBlueprintDraft activate(String finalConfigJson, Instant activatedAt, String operator) {
        return new CrawlerBlueprintDraft(
                code,
                name,
                entryUrl,
                concurrencyLimit,
                true,
                parserTemplateCode,
                finalConfigJson,
                finalConfigJson,
                lastTestReportJson,
                CrawlerBlueprintStatus.ACTIVE,
                true,
                operator == null ? generatedBy : operator,
                activatedAt,
                createdAt,
                activatedAt
        );
    }

    public CrawlerBlueprint toBlueprint(ParserProfile profile,
                                        PagingStrategy paging,
                                        CrawlFlow flow,
                                        AutomationSettings automation,
                                        Map<String, Object> metadata,
                                        CrawlBlueprint.RateLimit rateLimit) {
        Objects.requireNonNull(profile, "profile");
        return new CrawlBlueprint(
                code,
                name,
                enabled,
                concurrencyLimit,
                entryUrl,
                paging,
                flow,
                profile,
                rateLimit,
                metadata,
                automation,
                status,
                draftConfigJson,
                lastTestReportJson,
                autoGenerated,
                generatedBy,
                generatedAt
        );
    }
}
