version: "3.9"
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-vibejobs}
      MYSQL_USER: ${MYSQL_USER:-vibejobs}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-vibejobs}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  caddy:
    image: caddy:2
    restart: always
    ports: ["80:80","443:443"]
    environment: [ "DOMAIN=${DOMAIN}", "EMAIL=${EMAIL}" ]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on: [ frontend, backend ]

  backend:
    build:
      context: ./vibe-jobs-aggregator           # ← 后端源码真实目录
      dockerfile: ../docker/backend.Dockerfile   # ← 使用根目录的 Dockerfile
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_DATABASE_PLATFORM=${SPRING_JPA_DATABASE_PLATFORM}
      - SPRING_FLYWAY_SCHEMAS=${SPRING_FLYWAY_SCHEMAS}
      - JAVA_OPTS=${JAVA_OPTS:-}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_BASE_URL=${DEEPSEEK_BASE_URL:-https://api.deepseek.com}
      - DEEPSEEK_CHAT_COMPLETIONS_PATH=${DEEPSEEK_CHAT_COMPLETIONS_PATH:-/chat/completions}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL:-deepseek-chat}
      - DEEPSEEK_TIMEOUT=${DEEPSEEK_TIMEOUT:-PT45S}
      - DEEPSEEK_TEMPERATURE=${DEEPSEEK_TEMPERATURE:-0.2}
      - DEEPSEEK_MAX_OUTPUT_TOKENS=${DEEPSEEK_MAX_OUTPUT_TOKENS:-800}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com}
      - OPENAI_RESPONSES_PATH=${OPENAI_RESPONSES_PATH:-/v1/responses}
      - OPENAI_CHAT_COMPLETIONS_PATH=${OPENAI_CHAT_COMPLETIONS_PATH:-/v1/chat/completions}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OPENAI_TIMEOUT=${OPENAI_TIMEOUT:-PT20S}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.2}
      - OPENAI_MAX_OUTPUT_TOKENS=${OPENAI_MAX_OUTPUT_TOKENS:-800}
   #   - DB_AES_KEY_PATH=/app/secrets/db-aes.key
   # volumes:
    # - /opt/vibejobs/secrets:/app/secrets:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"     # 单个日志文件最大 100MB
        max-file: "10"       # 最多保留 10 个轮转日志文件
    expose: ["8080"]
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./vibe-jobs-view                 # ← 前端源码真实目录
      dockerfile: ../docker/frontend.Dockerfile
    restart: always
    environment:
      - BACKEND_BASE_URL=http://backend:8080
      - NEXT_PUBLIC_BACKEND_BASE=/api
      - PORT=3000
    logging:
      driver: "json-file"
      options:
        max-size: "100m"     # 单个日志文件最大 100MB
        max-file: "10"       # 最多保留 10 个轮转日志文件
    expose: ["3000"]
    depends_on: [ backend ]

volumes:
  caddy-data:
  caddy-config:
  mysql-data:
