version: "3.9"
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-vibejobs}
      MYSQL_USER: ${MYSQL_USER:-vibejobs}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-vibejobs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  caddy:
    image: caddy:2
    restart: always
    ports: ["80:80","443:443"]
    environment: [ "DOMAIN=${DOMAIN}", "EMAIL=${EMAIL}" ]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on: [ frontend, backend ]

  backend:
    build:
      context: ./vibe-jobs-aggregator           # ← 后端源码真实目录
      dockerfile: ../docker/backend.Dockerfile   # ← 使用根目录的 Dockerfile
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_DATABASE_PLATFORM=${SPRING_JPA_DATABASE_PLATFORM}
    expose: ["8080"]
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./vibe-jobs-view                 # ← 前端源码真实目录
      dockerfile: ../docker/frontend.Dockerfile
    restart: always
    environment:
      - BACKEND_BASE_URL=http://backend:8080
      - NEXT_PUBLIC_BACKEND_BASE=/api
      - PORT=3000
    expose: ["3000"]
    depends_on: [ backend ]

volumes:
  caddy-data:
  caddy-config:
  mysql-data:
