spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL:jdbc:h2:file:./data/jobsdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:sa}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  mail:
    host: smtp.qq.com
    port: 465
    username: 975022570@qq.com
    password: whryriubzonmbcic
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.port: 465
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:mysql}
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/api}
ingestion:
  fixedDelayMs: 180000
  initialDelayMs: 10000
  pageSize: 100
  concurrency: 6
  mode: companies
  companies:
    - "adyen"
    - "airwallex"
    - "airbnb"
    - "airtable"
    - "binance"
    - "brex"
    - "bybit"
    - "chainalysis"
    - "checkoutcom"
    - "circle"
    - "coinbase"
    - "crypto"
    - "databricks"
    - "datadog"
    - "figma"
    - "flexport"
    - "grab"
    - "lalamove"
    - "linear"
    - "notion"
    - "okx"
    - "palantir"
    - "paypal"
    - "revolut"
    - "shopback"
    - "shopify"
    - "snowflake"
    - "stripe"
    - "thunes"
    - "uber"
    - "visa"
    - "wise"
    - "webflow"
    - "xendit"
    - "zendesk"
    - "xiaohongshu"
    - "zhihu"
    - "kuaishou"
    - "meituan"
    - "pingcap"
    - "bytedance"
    - "xiaomi"
    - "oppo"
    - "vivo"
    - "nio"
    - "dji"
    - "shein"
    - "pdd"
    - "baidu"
    - "jd"
  recentDays: 45
  locationFilter:
    enabled: ${LOCATION_FILTER_ENABLED:true}
    includeCountries:
      - "china"
      - "中国"
      - "hong kong"
      - "香港"
      - "taiwan"
      - "singapore"
      - "malaysia"
      - "thailand"
    includeCities:
      - "beijing"
      - "北京"
      - "shanghai"
      - "上海"
      - "shenzhen"
      - "深圳"
      - "guangzhou"
      - "广州"
      - "hangzhou"
      - "杭州"
      - "chengdu"
      - "成都"
      - "nanjing"
      - "南京"
      - "suzhou"
      - "苏州"
      - "tianjin"
      - "天津"
      - "wuhan"
      - "武汉"
      - "chongqing"
      - "重庆"
      - "xi'an"
      - "西安"
      - "qingdao"
      - "青岛"
      - "dalian"
      - "大连"
      - "hong kong"
      - "hong-kong"
      - "singapore"
      - "remote - china"
      - "remote china"
      - "greater china"
    includeKeywords:
      - "china"
      - "中国"
      - "hong kong"
      - "香港"
      - "asia pacific"
      - "apac"
      - "大陆"
      - "大中华"
    excludeKeywords:
      - "us only"
      - "usa only"
      - "north america only"
      - "europe only"
      - "must be located in us"
      - "require us work authorization"
      - "eu citizens only"
      - "sales"
      - "marketing"
      - "hr"
      - "legal"
      - "customer success"
  roleFilter:
    enabled: ${ROLE_FILTER_ENABLED:true}
    searchDescription: true
    includeKeywords:
      - "financial"
      - "finance"
      - "analyst"
      - "investment"
      - "accounting"
      - "treasury"
      - "财务"
      - "金融"
      - "分析师"
      - "投资"
      - "engineer"
      - "工程师"
      - "developer"
      - "软件"
      - "后端"
      - "前端"
      - "全栈"
      - "数据"
      - "算法"
      - "machine learning"
      - "devops"
      - "sre"
      - "platform"
      - "云计算"
      - "ai"
    excludeKeywords:
      - "intern"
      - "internship"
      - "graduate program"
      - "校园"
      - "campus"
      - "实习"
      - "temporary"
      - "sales"
      - "marketing"
      - "hr"
      - "legal"
      - "customer success"
  sources:
    - id: greenhouse
      type: greenhouse
      enabled: true
      runOnStartup: true
    - id: lever
      type: lever
      enabled: false
      runOnStartup: false
    - id: workday
      type: workday
      enabled: true
      runOnStartup: true
      requireOverride: true
    - id: ashby
      type: ashby
      enabled: true
      runOnStartup: true
      requireOverride: true
  companyOverrides:
    notion:
      sources:
        ashby:
          options:
            baseUrl: "https://jobs.ashbyhq.com/notion"
    figma:
      sources:
        ashby:
          options:
            baseUrl: "https://jobs.ashbyhq.com/figma"
    linear:
      sources:
        ashby:
          options:
            baseUrl: "https://jobs.ashbyhq.com/linear"
    airtable:
      sources:
        ashby:
          options:
            baseUrl: "https://jobs.ashbyhq.com/airtable"
    webflow:
      sources:
        ashby:
          options:
            baseUrl: "https://jobs.ashbyhq.com/webflow"
    adyen:
      sources:
        workday:
          enabled: true
          options:
            baseUrl: "https://adyen.wd3.myworkdayjobs.com"
            tenant: "adyen"
            site: "AdyenCareers"
    grab:
      sources:
        workday:
          enabled: true
          options:
            baseUrl: "https://grab.wd3.myworkdayjobs.com"
            tenant: "grab"
            site: "GrabCareers"
    paypal:
      sources:
        workday:
          enabled: true
          options:
            baseUrl: "https://paypal.wd1.myworkdayjobs.com"
            tenant: "paypal"
            site: "External"
    revolut:
      sources:
        workday:
          enabled: true
          options:
            baseUrl: "https://revolut.wd3.myworkdayjobs.com"
            tenant: "revolut"
            site: "RevolutCareers"
    stripe:
      sources:
        workday:
          enabled: true
          options:
            baseUrl: "https://stripe.wd1.myworkdayjobs.com"
            tenant: "stripe"
            site: "Stripe_Careers"
    visa:
      sources:
        workday:
          enabled: true
          options:
            baseUrl: "https://visa.wd1.myworkdayjobs.com"
            tenant: "visa"
            site: "External"
    wise:
      sources:
        workday:
          enabled: true
          options:
            baseUrl: "https://wise.wd3.myworkdayjobs.com"
            tenant: "wise"
            site: "Wise"
      categories:
        - name: "{{company}} Engineering"
          limit: 40
          tags:
            - engineering
            - software
          facets:
            jobFamily:
              - Engineering
        - name: "{{company}} Financial"
          limit: 20
          tags:
            - finance
            - financial

auth:
  email:
    challengeTtl: PT10M
    resendCooldown: PT60S
    sessionTtl: P30D
    exposeCodeInResponse: true
    fromAddress: 975022570@qq.com
    sender: ${AUTH_EMAIL_SENDER:smtp}
