spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL:jdbc:h2:file:./data/jobsdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:sa}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  mail:
    host: smtp.qq.com
    port: 465
    username: 975022570@qq.com
    password: whryriubzonmbcic
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.port: 465
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:h2}
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/api}
ingestion:
  fixedDelayMs: 300000
  initialDelayMs: 10000
  pageSize: 50
  concurrency: 4
  mode: companies
  companies:
    - "akunacapital"
    - "adyen"
    - "affirm"
    - "afterpay"
    - "airwallex"
    - "airtable"
    - "algolia"
    - "alphasense"
    - "alphasights"
    - "ambergroup"
    - "anchorage"
    - "appsflyer"
    - "asana"
    - "atlassian"
    - "binance"
    - "bitgo"
    - "bitmex"
    - "bitpanda"
    - "block"
    - "blockdaemon"
    - "blockchain"
    - "blockfi"
    - "blockstream"
    - "bolt"
    - "brex"
    - "bybit"
    - "canva"
    - "carta"
    - "chainalysis"
    - "chainstack"
    - "checkoutcom"
    - "chime"
    - "chippercash"
    - "circle"
    - "codapayments"
    - "coinbase"
    - "coinlist"
    - "crypto"
    - "currencycloud"
    - "databricks"
    - "datadog"
    - "dataminr"
    - "deliveroo"
    - "dlocal"
    - "doordash"
    - "drw"
    - "elliptic"
    - "figma"
    - "fireblocks"
    - "flowtraders"
    - "flexport"
    - "five-rings"
    - "gojek"
    - "grab"
    - "gocardless"
    - "gusto"
    - "hashicorp"
    - "hudsonrivertrading"
    - "imcfinancialmarkets"
    - "intercom"
    - "janestreet"
    - "jumptrading"
    - "klarna"
    - "klook"
    - "kraken"
    - "lalamove"
    - "ledger"
    - "lendingclub"
    - "liveramp"
    - "luno"
    - "mambu"
    - "marqeta"
    - "mastercard"
    - "mongodb"
    - "monzo"
    - "n26"
    - "nium"
    - "notion"
    - "nubank"
    - "okx"
    - "onfido"
    - "opensea"
    - "optiver"
    - "palantir"
    - "patsnap"
    - "paxos"
    - "paypal"
    - "pipedrive"
    - "plaid"
    - "point72"
    - "rapyd"
    - "reddit"
    - "remitly"
    - "revolut"
    - "ripple"
    - "rippling"
    - "robinhood"
    - "rokt"
    - "shopback"
    - "shopify"
    - "shopee"
    - "snowflake"
    - "sofi"
    - "squareup"
    - "stripe"
    - "sumup"
    - "taboola"
    - "tala"
    - "thoughtmachine"
    - "thunes"
    - "transfergo"
    - "trmlabs"
    - "truelayer"
    - "twosigma"
    - "uber"
    - "upwork"
    - "visa"
    - "virtu"
    - "wework"
    - "wise"
    - "worldquant"
    - "xendit"
    - "xero"
    - "yelp"
    - "zendesk"
    - "zillow"
  recentDays: 7
  sources:
    - id: greenhouse
      type: greenhouse
      enabled: true
      runOnStartup: true
      options:
        slug: "{{slug}}"
    - id: lever
      type: lever
      enabled: true
      runOnStartup: true
      options:
        company: "{{slug}}"
    - id: workday
      type: workday
      enabled: true
      runOnStartup: true
      requireOverride: true
      options:
        baseUrl: "https://{{slug}}.wd1.myworkdayjobs.com"
        tenant: "{{slug}}"
        site: "{{slugUpper}}"
  companyOverrides:
    adyen:
      sources:
        greenhouse:
          enabled: false
        lever:
          enabled: false
        workday:
          options:
            baseUrl: "https://adyen.wd3.myworkdayjobs.com"
            tenant: "adyen"
            site: "AdyenCareers"
    grab:
      sources:
        greenhouse:
          enabled: false
        lever:
          enabled: false
        workday:
          options:
            baseUrl: "https://grab.wd3.myworkdayjobs.com"
            tenant: "grab"
            site: "GrabCareers"
    mastercard:
      sources:
        greenhouse:
          enabled: false
        lever:
          enabled: false
        workday:
          options:
            baseUrl: "https://mastercard.wd1.myworkdayjobs.com"
            tenant: "mastercard"
            site: "CorporateCareers"
    paypal:
      sources:
        greenhouse:
          enabled: false
        lever:
          enabled: false
        workday:
          options:
            baseUrl: "https://paypal.wd1.myworkdayjobs.com"
            tenant: "paypal"
            site: "External"
    revolut:
      sources:
        greenhouse:
          enabled: false
        lever:
          enabled: false
        workday:
          options:
            baseUrl: "https://revolut.wd3.myworkdayjobs.com"
            tenant: "revolut"
            site: "RevolutCareers"
    stripe:
      sources:
        greenhouse:
          enabled: false
        lever:
          enabled: false
        workday:
          options:
            baseUrl: "https://stripe.wd1.myworkdayjobs.com"
            tenant: "stripe"
            site: "Stripe_Careers"
    visa:
      sources:
        greenhouse:
          enabled: false
        lever:
          enabled: false
        workday:
          options:
            baseUrl: "https://visa.wd1.myworkdayjobs.com"
            tenant: "visa"
            site: "External"
    wise:
      sources:
        greenhouse:
          enabled: false
        lever:
          enabled: false
        workday:
          options:
            baseUrl: "https://wise.wd3.myworkdayjobs.com"
            tenant: "wise"
            site: "Wise"
      categories:
        - name: "{{company}} Engineering"
          limit: 40
          tags:
            - engineering
            - software
          facets:
            jobFamily:
              - Engineering
              - "{{companyUpper}} Technology"
        - name: "{{company}} Financial"
          limit: 20
          tags:
            - finance
            - financial


auth:
  email:
    challengeTtl: PT10M
    resendCooldown: PT60S
    sessionTtl: P30D
    exposeCodeInResponse: true
    fromAddress: 975022570@qq.com
