
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL:jdbc:h2:file:./data/jobsdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:sa}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/api}
ingestion:
  fixedDelayMs: 300000
  initialDelayMs: 10000
  pageSize: 50
  concurrency: 4
  mode: companies
  companies:
    - "Micron"
#    - "HSBC"
#    - "Standard Chartered"
#    - "Citibank"
#    - "Bank of America"
#    - "Barclays"
#    - "Deutsche Bank"
#    - "BNP Paribas"
#    - "Societe Generale"
#    - "Credit Agricole CIB"
#    - "Natixis"
#    - "ING Bank"
#    - "Rabobank"
#    - "ABN AMRO"
#    - "Banco Santander"
#    - "BBVA"
#    - "Royal Bank of Canada"
#    - "Bank of Montreal"
#    - "Toronto-Dominion Bank"
#    - "Scotiabank"
#    - "ANZ"
#    - "Commonwealth Bank of Australia"
#    - "Westpac"
#    - "National Australia Bank"
#    - "Macquarie Group"
#    - "Mitsubishi UFJ Financial Group"
#    - "Sumitomo Mitsui Banking Corporation"
#    - "Mizuho Financial Group"
#    - "Nomura Holdings"
#    - "Daiwa Securities Group"
#    - "Orix Corporation"
#    - "Bank of New York Mellon"
#    - "State Street Corporation"
#    - "Northern Trust"
#    - "First Abu Dhabi Bank"
#    - "Emirates NBD"
#    - "Qatar National Bank"
#    - "United Overseas Bank"
#    - "DBS Bank"
#    - "OCBC Bank"
#    - "Maybank"
#    - "CIMB Bank"
#    - "Industrial Bank of Korea"
#    - "KB Kookmin Bank"
#    - "Shinhan Bank"
#    - "Woori Bank"
#    - "Hana Bank"
#    - "ICICI Bank"
#    - "HDFC Bank"
#    - "Axis Bank"
#    - "Bank of Baroda"
#    - "Standard Bank Group"
#    - "Hang Seng Bank"
#    - "Bank of East Asia"
#    - "Banco do Brasil"
#    - "Itaú Unibanco"
#    - "Canadian Imperial Bank of Commerce"
#    - "SEB"
#    - "Nordea"
#    - "Swedbank"
#    - "Handelsbanken"
#    - "DNB ASA"
#    - "Erste Group Bank"
#    - "Raiffeisen Bank International"
#    - "UniCredit"
#    - "Intesa Sanpaolo"
#    - "NatWest Group"
#    - "Lazard"
#    - "Jefferies"
#    - "Houlihan Lokey"
#    - "Rothschild & Co"
#    - "Moelis & Company"
#    - "Evercore"
#    - "Guggenheim Partners"
#    - "PJT Partners"
#    - "Citadel Securities"
#    - "BlackRock"
#    - "Vanguard"
#    - "Fidelity Investments"
#    - "Schroders"
#    - "abrdn"
#    - "Invesco"
#    - "T. Rowe Price"
#    - "Franklin Templeton"
#    - "Wellington Management"
#    - "AllianceBernstein"
#    - "Janus Henderson Investors"
#    - "Legg Mason"
#    - "Nuveen"
#    - "PIMCO"
#    - "DWS Group"
#    - "Amundi"
#    - "AXA Investment Managers"
#    - "Allianz Global Investors"
#    - "Generali Investments"
#    - "Manulife Investment Management"
#    - "Sun Life Financial"
#    - "Principal Financial Group"
#    - "MetLife Investment Management"
#    - "Prudential plc"
#    - "Aviva Investors"
#    - "AIA Group"
#    - "Zurich Insurance Group"
#    - "Swiss Re"
#    - "Munich Re"
#    - "Hannover Re"
#    - "SCOR"
#    - "Tokio Marine Holdings"
#    - "Sompo Holdings"
#    - "MS&AD Insurance Group"
#    - "Dai-ichi Life"
#    - "Nippon Life"
#    - "Meiji Yasuda Life"
#    - "FWD Group"
#    - "MassMutual"
#    - "New York Life"
#    - "AIG"
#    - "Chubb"
#    - "Liberty Mutual Insurance"
#    - "Travelers"
#    - "AXIS Capital"
#    - "Arch Capital Group"
#    - "Blackstone"
#    - "KKR"
#    - "The Carlyle Group"
#    - "Apollo Global Management"
#    - "Brookfield Asset Management"
#    - "Bain Capital"
#    - "Warburg Pincus"
#    - "TPG"
#    - "Partners Group"
#    - "EQT"
#    - "CVC Capital Partners"
#    - "Advent International"
#    - "Ardian"
#    - "Oaktree Capital Management"
#    - "Temasek"
#    - "GIC"
#    - "CPP Investments"
#    - "Ontario Teachers' Pension Plan"
#    - "CDPQ"
#    - "Abu Dhabi Investment Authority"
#    - "Mubadala Investment Company"
#    - "Qatar Investment Authority"
#    - "McKinsey & Company"
#    - "Boston Consulting Group"
#    - "Bain & Company"
#    - "Accenture"
#    - "Capgemini"
#    - "Deloitte"
#    - "PwC"
#    - "EY"
#    - "KPMG"
#    - "Roland Berger"
#    - "Oliver Wyman"
#    - "Strategy&"
#    - "L.E.K. Consulting"
#    - "Alvarez & Marsal"
#    - "AlixPartners"
#    - "Protiviti"
#    - "FTI Consulting"
#    - "Guidehouse"
#    - "Mercer"
#    - "Aon"
#    - "Willis Towers Watson"
#    - "Marsh & McLennan Companies"
#    - "Korn Ferry"
#    - "Heidrick & Struggles"
#    - "Spencer Stuart"
#    - "Egon Zehnder"
#    - "Robert Half"
#    - "ManpowerGroup"
#    - "Randstad"
#    - "Adecco Group"
#    - "Hays"
#    - "PageGroup (Michael Page)"
#    - "SThree"
#    - "Kelly Services"
#    - "Hudson Global"
#    - "Allegis Group"
#    - "RGP (Resources Global Professionals)"
#    - "Visa"
#    - "Mastercard"
#    - "American Express"
#    - "Discover Financial Services"
#    - "PayPal"
#    - "Payoneer"
#    - "Western Union"
#    - "Worldline"
#    - "Adyen"
#    - "Fiserv"
#    - "FIS"
#    - "Global Payments"
#    - "PayU"
#    - "Wise"
#    - "MoneyGram International"
#    - "Stripe"
#    - "Block"
#    - "Intuit"
#    - "Xero"
#    - "Sage Group"
  recentDays: 7
  sources:
    - id: greenhouse
      type: greenhouse
      enabled: false
      runOnStartup: false
      options:
        slug: "{{slug}}"
    - id: lever
      type: lever
      enabled: false
      runOnStartup: false
      options:
        company: "{{slug}}"
    - id: workday
      type: workday
      enabled: true
      runOnStartup: true
      options:
        baseUrl: "https://{{slug}}.wd1.myworkdayjobs.com"
        tenant: "{{slug}}"
        site: "{{slugUpper}}"


auth:
  email:
    challengeTtl: PT10M
    resendCooldown: PT60S
    sessionTtl: P30D
    exposeCodeInResponse: true
    senderAddress: ${AUTH_EMAIL_SENDER_ADDRESS:}
