spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL:jdbc:mysql://localhost:3306/vibejobs?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:vibejobs}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:changeme}}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "Baseline existing schema"
    schemas: ${SPRING_FLYWAY_SCHEMAS:${DB_SCHEMA:jobs}}
    clean-disabled: true
