package com.vibe.jobs.crawler.infrastructure.jpa;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;

@Entity
@Table(name = "crawler_blueprint")
public class CrawlerBlueprintEntity {

    @Id
    @Column(length = 128)
    private String code;

    @Column(nullable = false, length = 256)
    private String name;

    @Column(nullable = false)
    private boolean enabled;

    @Column(name = "entry_url", length = 2048)
    private String entryUrl;

    @Column(name = "concurrency_limit")
    private int concurrencyLimit;

    @Column(name = "config_json", columnDefinition = "LONGTEXT")
    private String configJson;

    @Column(name = "parser_template_code", length = 128)
    private String parserTemplateCode;

    @Column(length = 32, nullable = false)
    private String status;

    @Column(name = "draft_config_json", columnDefinition = "JSON")
    private String draftConfigJson;

    @Column(name = "last_test_report", columnDefinition = "JSON")
    private String lastTestReport;

    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated;

    @Column(name = "generated_by", length = 128)
    private String generatedBy;

    @Column(name = "generated_at")
    private Instant generatedAt;

    @Column(name = "created_at")
    private Instant createdAt;

    @Column(name = "updated_at")
    private Instant updatedAt;

    @PrePersist
    void onCreate() {
        Instant now = Instant.now();
        createdAt = now;
        updatedAt = now;
        if (status == null || status.isBlank()) {
            status = "ACTIVE";
        }
    }

    @PreUpdate
    void onUpdate() {
        updatedAt = Instant.now();
        if (status == null || status.isBlank()) {
            status = "ACTIVE";
        }
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public String getEntryUrl() {
        return entryUrl;
    }

    public void setEntryUrl(String entryUrl) {
        this.entryUrl = entryUrl;
    }

    public int getConcurrencyLimit() {
        return concurrencyLimit;
    }

    public void setConcurrencyLimit(int concurrencyLimit) {
        this.concurrencyLimit = concurrencyLimit;
    }

    public String getConfigJson() {
        return configJson;
    }

    public void setConfigJson(String configJson) {
        this.configJson = configJson;
    }

    public String getParserTemplateCode() {
        return parserTemplateCode;
    }

    public void setParserTemplateCode(String parserTemplateCode) {
        this.parserTemplateCode = parserTemplateCode;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDraftConfigJson() {
        return draftConfigJson;
    }

    public void setDraftConfigJson(String draftConfigJson) {
        this.draftConfigJson = draftConfigJson;
    }

    public String getLastTestReport() {
        return lastTestReport;
    }

    public void setLastTestReport(String lastTestReport) {
        this.lastTestReport = lastTestReport;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public String getGeneratedBy() {
        return generatedBy;
    }

    public void setGeneratedBy(String generatedBy) {
        this.generatedBy = generatedBy;
    }

    public Instant getGeneratedAt() {
        return generatedAt;
    }

    public void setGeneratedAt(Instant generatedAt) {
        this.generatedAt = generatedAt;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }
}
