package com.vibe.jobs.admin.web.dto;

import com.vibe.jobs.crawler.domain.CrawlerBlueprintDraft;
import com.vibe.jobs.crawler.domain.CrawlerBlueprintStatus;

import java.time.Instant;

public record CrawlerBlueprintSummaryResponse(
        String code,
        String name,
        String entryUrl,
        boolean enabled,
        CrawlerBlueprintStatus status,
        boolean autoGenerated,
        String generatedBy,
        Instant generatedAt,
        Instant createdAt,
        Instant updatedAt
) {
    public static CrawlerBlueprintSummaryResponse fromDomain(CrawlerBlueprintDraft draft) {
        return new CrawlerBlueprintSummaryResponse(
                draft.code(),
                draft.name(),
                draft.entryUrl(),
                draft.enabled(),
                draft.status(),
                draft.autoGenerated(),
                draft.generatedBy(),
                draft.generatedAt().orElse(null),
                draft.createdAt().orElse(null),
                draft.updatedAt().orElse(null)
        );
    }
}
